import {
    faArrowRightFromBracket,
    faBookBookmark,
    faCircleExclamation,
    faClipboardCheck,
    faKey,
    faLocationDot,
    faShop,
    faTriangleExclamation,
    faUser,
    faWallet,
    faChartSimple,
} from '@fortawesome/free-solid-svg-icons';
import images from '~/assets/images/image';

const listUser = [
    {
        id: 111,
        roll: 'admin',
        password: '123',
    },
    {
        id: 23,
        status: 'block',
        name: 'Nguyễn Văn Mười',
        avatar: images.avatarStore,
        password: '123',
        email: 'nguyenvana@gmail.com',
        address: 'Quảng Ngãi',
        area: 'quangngai',
    },
    {
        id: 1001,
        name: 'Nguyễn Văn A',
        avatar: images.avatarStore,
        password: 'a123',
        email: 'nguyenvana@gmail.com',
        area: 'hue',
        phone: '0367376403',
        address: 'Huế',
        sex: 0,
    },
    {
        id: 1002,
        name: 'Trần Thị B',
        avatar: images.avatarStore,
        password: 'b123',
        email: 'tranthib@gmail.com',
        area: 'danang',
        phone: '0367376403',
        address: 'Đà Nẵng',
        sex: 1,
    },
    {
        id: 1003,
        name: 'Lê Văn C',
        avatar: images.avatarStore,
        password: 'c123',
        email: 'levanc@gmail.com',
        area: 'quangnam',
        phone: '0367376403',
        address: 'Quảng Nam',
        sex: 0,
    },
    {
        id: 1004,
        name: 'Phạm Thị D',
        avatar: images.avatarStore,
        password: 'd123',
        email: 'phamthid@gmail.com',
        area: 'hue',
        phone: '0367376403',
        address: 'Huế',
        sex: 1,
    },
    {
        id: 1005,
        name: 'Đặng Văn E',
        avatar: images.avatarStore,
        password: 'e123',
        email: 'dangvane@gmail.com',
        area: 'hatinh',
        phone: '0367376403',
        address: 'Hà Tĩnh',
        sex: 0,
    },
    {
        id: 1006,
        name: 'Đặng Văn E',
        avatar: images.avatarStore,
        password: 'e123',
        email: 'dangvane@gmail.com',
        address: 'Xã Quảng Điền, TP Huế',
        area: 'hue',
    },
    {
        id: 1007,
        name: 'Đặng Văn Em',
        status: 'block',
        avatar: images.avatarStore,
        password: 'e123',
        email: 'dangvane@gmail.com',
        address: 'Xã Quảng Điền, TP Huế',
        area: 'hue',
    },
];

const listSidebarProfileUser = [
    {
        id: 1,
        name: 'Hồ sơ của tôi',
        icon: faUser,
        path: '/UserProfileInfo',
    },
    {
        id: 2,
        name: 'Địa chỉ giao hàng',
        icon: faLocationDot,
        path: '/UserProfileAddress',
    },
    {
        id: 3,
        name: 'Đổi mật khẩu',
        icon: faKey,
        path: '/UserProfilePassword',
    },
    {
        id: 4,
        name: 'Đơn hàng',
        icon: faClipboardCheck,
        path: '/UserProfileOrder',
    },
    {
        id: 5,
        name: 'Sản phẩm yêu thích',
        icon: faBookBookmark,
        path: '/UserProfileFavoriteProduct',
    },
    {
        id: 6,
        name: 'Cửa hàng yêu thích',
        icon: faShop,
        path: '/UserProfileFavoriteShop',
    },
    {
        id: 7,
        name: 'Đăng xuất',
        icon: faArrowRightFromBracket,
        path: '/',
    },
];
const listSidebarProfileSell = [
    {
        id: 1,
        name: 'Hồ sơ của tôi',
        icon: faUser,
        path: '/ProfileSell',
    },
    {
        id: 2,
        name: 'Cửa hàng của tôi',
        icon: faShop,
        path: '/StoreSell',
    },
    {
        id: 3,
        name: 'Đổi mật khẩu',
        icon: faKey,
        path: '/PasswordSell',
    },
    {
        id: 4,
        name: 'Thống Kê',
        icon: faChartSimple,
        path: '/StatisticSell',
    },
    {
        id: 5,
        name: 'Duyệt đơn hàng',
        icon: faClipboardCheck,
        path: '/OrderSell',
    },
    {
        id: 6,
        name: 'Ví',
        icon: faWallet,
        path: '/WalletSell',
    },
    {
        id: 7,
        name: 'Đăng xuất',
        icon: faArrowRightFromBracket,
        path: '/',
    },
];

const listMenuUser = [
    { name: 'Trang Chủ', path: '/UserHome' },
    {
        name: 'Sản Phẩm',
        path: '/UserProduct',
        children: [
            {
                name: 'Đồ khô - Chế biến sẵn',
                path: '/UserProduct?category=dried',
                categoryKey: 'dried',
            },
            {
                name: 'Bánh - Kẹo',
                path: '/UserProduct?category=snacks',
                categoryKey: 'snacks',
            },
            {
                name: 'Trái Cây - Rau Củ',
                path: '/UserProduct?category=fruits',
                categoryKey: 'fruits',
            },
            {
                name: 'Gia vị',
                path: '/UserProduct?category=spices',
                categoryKey: 'spices',
            },
            {
                name: 'Đồ uống',
                path: '/UserProduct?category=drinks',
                categoryKey: 'drinks',
            },
        ],
    },
    { name: 'Giới Thiệu', path: '/UserIntroduce' },
];

const listMenuAdmin = [
    { name: 'Thống Kế', path: '/StatisAdmin' },
    {
        name: 'Quản Lý',
        path: '/ManagerUser',
        children: [
            {
                name: 'Người Dùng',
                path: '/ManagerUser',
            },
            {
                name: 'Cửa Hàng',
                path: '/ManagerSell',
            },
        ],
    },
    { name: 'Giới Thiệu', path: '/IntroduceAdmin' },
];

const listMenuSell = [
    { name: 'Sản Phẩm', path: '/ProductSell' },
    { name: 'Giới Thiệu', path: '/IntroduceSell' },
];
const listSliderBarSell = [
    { name: 'Hồ sơ của tôi', path: '/ProfileSell' },
    { name: 'Cửa hàng của tôi', path: '/StoreSell' },
    { name: 'Đổi mật khẩu', path: '/PasswordSell' },
    { name: 'Thống kê', path: '/StatisticSell' },
    { name: 'Duyệt đơn hàng', path: '/OrderSell' },
    { name: 'Ví', path: '/WalletSell' },
    { name: 'Đăng xuất', path: '/' },
];

const storeList = [
    {
        id: 1,
        idBank: 1,
        name: 'Bếp Nhà',
        description:
            'Bếp Nhà là nơi lưu giữ và lan tỏa những hương vị đặc sản đậm chất miền Trung Việt Nam. Từ những món quà quê dân dã đến các sản phẩm truyền thống được chế biến tinh tế, chúng tôi mong muốn mang đến cho bạn không chỉ là món ăn, mà còn là một phần ký ức, một chút ấm áp của quê hương.',
        address: '125 Trường Chinh, TP. Huế',
        phone: '0935 123 456',
        email: 'contact@bepnha.vn',
        website: 'https://www.bepnha.vn',
        fanpage: 'https://www.fb.com/bepnhadacsan',
        rating: 4.8,
        totalReviews: 898,
        joinedAt: '2018-08-01',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: ['Mè xửng Huế', 'Me xí muội Huế', 'Trà Huế'],
        guarantee: [
            'Nguyên liệu sạch, chuẩn vị quê nhà',
            'Đóng gói kỹ lưỡng, giao hàng toàn quốc',
            'Tư vấn tận tình, đổi trả dễ dàng nếu sản phẩm không như cam kết',
        ],
        area: 'hue',
        status: 'approved',
    },
    {
        id: 2,
        name: 'Đặc Sản Đà Nẵng',
        description:
            'Mang hương vị của thành phố biển đến từng bữa ăn, Đặc Sản Đà Nẵng chuyên cung cấp các sản phẩm như nước mắm Nam Ô, tré Bà Đệ, bánh khô mè truyền thống.',
        address: '78 Nguyễn Văn Linh, TP. Đà Nẵng',
        phone: '0905 234 567',
        email: 'contact@dacsandanang.vn',
        website: 'https://www.dacsandanang.vn',
        fanpage: 'https://www.fb.com/dacsandanang',
        rating: 4.5,
        totalReviews: 500,
        joinedAt: '2019-05-15',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Nước mắm Nam Ô',
            'Tré Bà Đệ',
            'Bánh khô mè',
            'Chả bò Đà Nẵng',
        ],
        guarantee: [
            'Chọn lọc từ vùng biển Đà Nẵng',
            'Chế biến an toàn, đóng gói kỹ',
            'Hoàn tiền nếu sản phẩm không đúng mô tả',
        ],
        area: 'danang',
        status: 'approved',
    },
    {
        id: 3,
        name: 'Quảng Nam Quê Tôi',
        description:
            'Gìn giữ hương vị dân dã của vùng đất Quảng Nam qua từng món đặc sản như bánh tráng mè, mỳ Quảng, bánh tổ, bánh in truyền thống.',
        address: '45 Trần Cao Vân, Tam Kỳ, Quảng Nam',
        phone: '0911 111 222',
        email: 'info@quangnamquetoi.vn',
        website: 'https://www.quangnamquetoi.vn',
        fanpage: 'https://www.fb.com/quangnamquetoi',
        rating: 4.2,
        totalReviews: 310,
        joinedAt: '2020-02-10',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Bánh tráng mè nướng Quảng Nam',
            'Bánh tổ',
            'Mỳ Quảng',
        ],
        guarantee: [
            'Chế biến theo công thức gia truyền',
            'Sạch, ngon, đúng vị quê hương',
            'Hỗ trợ đổi trả trong 7 ngày',
        ],
        area: 'quangnam',
        status: 'approved',
    },
    {
        id: 4,
        name: 'Hà Tĩnh Đặc Sản',
        description:
            'Hà Tĩnh Đặc Sản là nơi hội tụ những món ngon nổi tiếng như kẹo cu đơ, cam Khe Mây, bánh đa, tương Nam Đàn, gói ghém hương vị miền Trung xa xứ.',
        address: '10 Lê Duẩn, TP. Hà Tĩnh',
        phone: '0922 333 444',
        email: 'support@hattinhdacsan.vn',
        website: 'https://www.hattinhdacsan.vn',
        fanpage: 'https://www.fb.com/hattinhdacsan',
        rating: 4.1,
        totalReviews: 180,
        joinedAt: '2021-04-05',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: ['Kẹo cu đơ Hà Tĩnh', 'Cam Khe Mây', 'Tương Nam Đàn'],
        guarantee: [
            'Nguyên liệu bản địa, quy trình thủ công',
            'Hương vị truyền thống, đóng gói chuẩn',
            'Hoàn tiền nếu sản phẩm không đạt yêu cầu',
        ],
        area: 'hatinh',
        status: 'block',
    },
    {
        id: 5,
        name: 'Quảng Ngãi Quê Hương',
        description:
            'Đưa đặc sản Quảng Ngãi đến gần hơn với mọi miền, chúng tôi cung cấp các sản phẩm như kẹo gương, kẹo đậu phộng, cá bống sông Trà, mạch nha,...',
        address: '66 Hùng Vương, TP. Quảng Ngãi',
        phone: '0988 555 666',
        email: 'hello@quangngai.vn',
        website: 'https://www.quangngai.vn',
        fanpage: 'https://www.fb.com/quangngaiquehuong',
        rating: 4.3,
        totalReviews: 250,
        joinedAt: '2019-11-20',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Kẹo đậu phộng Quảng Ngãi',
            'Cá bống sông Trà',
            'Mạch nha Quảng Ngãi',
        ],
        guarantee: [
            'Chọn lọc kỹ lưỡng từ địa phương',
            'Đóng gói an toàn, giữ trọn hương vị',
            'Đổi trả nếu không hài lòng',
        ],
        area: 'quangngai',
        status: 'cancelled',
    },
    {
        id: 6,
        name: 'Bếp Nhà',
        description:
            'Bếp Nhà là nơi lưu giữ và lan tỏa những hương vị đặc sản đậm chất miền Trung Việt Nam. Từ những món quà quê dân dã đến các sản phẩm truyền thống được chế biến tinh tế, chúng tôi mong muốn mang đến cho bạn không chỉ là món ăn, mà còn là một phần ký ức, một chút ấm áp của quê hương.',
        address: '125 Trường Chinh, TP. Huế',
        phone: '0935 123 456',
        email: 'contact@bepnha.vn',
        website: 'https://www.bepnha.vn',
        fanpage: 'https://www.fb.com/bepnhadacsan',
        rating: 4.8,
        totalReviews: 898,
        joinedAt: '2018-08-01',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: ['Mè xửng Huế', 'Me xí muội Huế', 'Trà Huế'],
        guarantee: [
            'Nguyên liệu sạch, chuẩn vị quê nhà',
            'Đóng gói kỹ lưỡng, giao hàng toàn quốc',
            'Tư vấn tận tình, đổi trả dễ dàng nếu sản phẩm không như cam kết',
        ],
        area: 'hue',
        status: 'cancelled',
    },
    {
        id: 7,
        name: 'Đặc Sản Đà Nẵng',
        description:
            'Mang hương vị của thành phố biển đến từng bữa ăn, Đặc Sản Đà Nẵng chuyên cung cấp các sản phẩm như nước mắm Nam Ô, tré Bà Đệ, bánh khô mè truyền thống.',
        address: '78 Nguyễn Văn Linh, TP. Đà Nẵng',
        phone: '0905 234 567',
        email: 'contact@dacsandanang.vn',
        website: 'https://www.dacsandanang.vn',
        fanpage: 'https://www.fb.com/dacsandanang',
        rating: 4.5,
        totalReviews: 500,
        joinedAt: '2019-05-15',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Nước mắm Nam Ô',
            'Tré Bà Đệ',
            'Bánh khô mè',
            'Chả bò Đà Nẵng',
        ],
        guarantee: [
            'Chọn lọc từ vùng biển Đà Nẵng',
            'Chế biến an toàn, đóng gói kỹ',
            'Hoàn tiền nếu sản phẩm không đúng mô tả',
        ],
        area: 'danang',
        status: 'approved',
    },
    {
        id: 8,
        name: 'Quảng Nam Quê Tôi',
        description:
            'Gìn giữ hương vị dân dã của vùng đất Quảng Nam qua từng món đặc sản như bánh tráng mè, mỳ Quảng, bánh tổ, bánh in truyền thống.',
        address: '45 Trần Cao Vân, Tam Kỳ, Quảng Nam',
        phone: '0911 111 222',
        email: 'info@quangnamquetoi.vn',
        website: 'https://www.quangnamquetoi.vn',
        fanpage: 'https://www.fb.com/quangnamquetoi',
        rating: 4.2,
        totalReviews: 310,
        joinedAt: '2020-02-10',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Bánh tráng mè nướng Quảng Nam',
            'Bánh tổ',
            'Mỳ Quảng',
        ],
        guarantee: [
            'Chế biến theo công thức gia truyền',
            'Sạch, ngon, đúng vị quê hương',
            'Hỗ trợ đổi trả trong 7 ngày',
        ],
        area: 'quangnam',
        status: 'approved',
    },
    {
        id: 9,
        name: 'Hà Tĩnh Đặc Sản',
        description:
            'Hà Tĩnh Đặc Sản là nơi hội tụ những món ngon nổi tiếng như kẹo cu đơ, cam Khe Mây, bánh đa, tương Nam Đàn, gói ghém hương vị miền Trung xa xứ.',
        address: '10 Lê Duẩn, TP. Hà Tĩnh',
        phone: '0922 333 444',
        email: 'support@hattinhdacsan.vn',
        website: 'https://www.hattinhdacsan.vn',
        fanpage: 'https://www.fb.com/hattinhdacsan',
        rating: 4.1,
        totalReviews: 180,
        joinedAt: '2021-04-05',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: ['Kẹo cu đơ Hà Tĩnh', 'Cam Khe Mây', 'Tương Nam Đàn'],
        guarantee: [
            'Nguyên liệu bản địa, quy trình thủ công',
            'Hương vị truyền thống, đóng gói chuẩn',
            'Hoàn tiền nếu sản phẩm không đạt yêu cầu',
        ],
        area: 'hatinh',
        status: 'approved',
    },
];

const listProduct = [
    {
        id: 1,
        name: 'Nước mắm Nam Ô',
        quantity: 50,
        price: 80000,
        description:
            'Nước mắm Nam Ô Đà Nẵng làm từ cá cơm than, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'danang',
        idStore: '2',
        image: [{ id: 1, url: images.nuocMam, alt: 'Nước mắm Nam Ô' }],
        totalStars: 100,
        reviews: 20, // lọc theo để hiển thị
    },
    {
        id: 2,
        name: 'Mè xửng Huế',
        quantity: 40,
        price: 65000,
        description:
            'Mè xửng dẻo thơm, vị ngọt bùi của mạch nha, mè rang vàng óng, đặc sản truyền thống xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXungHue, alt: 'Mè xửng Huế' }],
        totalStars: 120,
        reviews: 25,
    },
    {
        id: 3,
        name: 'Kẹo cu đơ Hà Tĩnh',
        quantity: 30,
        price: 180000,
        description:
            'Kẹo cu đơ giòn rụm, nhân lạc và mạch nha ngọt bùi, đặc sản nổi tiếng của Hà Tĩnh.',
        category: 'snacks',
        area: 'hatinh',
        idStore: '4',
        image: [{ id: 1, url: images.keoCuDo, alt: 'Kẹo cu đơ Hà Tĩnh' }],
        totalStars: 80,
        reviews: 18,
    },
    {
        id: 4,
        name: 'Bánh tráng mè nướng Quảng Nam',
        quantity: 70,
        price: 25000,
        description: 'Bánh tráng giòn rụm, thơm mùi mè rang đặc sản Quảng Nam.',
        category: 'snacks',
        area: 'quangnam',
        idStore: '3',
        image: [{ id: 1, url: images.banhTrang, alt: 'Bánh tráng mè nướng' }],
        totalStars: 80,
        reviews: 19,
    },
    {
        id: 5,
        name: 'Trà cung đình Huế',
        quantity: 90,
        price: 90000,
        description:
            'Trà thảo mộc cung đình Huế kết hợp nhiều loại dược liệu quý.',
        category: 'drinks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.tra, alt: 'Trà cung đình Huế' }],
        totalStars: 100,
        reviews: 21,
    },
    {
        id: 6,
        name: 'Kẹo đậu phộng Quảng Ngãi',
        quantity: 100,
        price: 20000,
        description:
            'Kẹo truyền thống làm từ đậu phộng và đường mạch nha đặc sản Quảng Ngãi.',
        category: 'snacks',
        area: 'quangngai',
        idStore: '5',
        image: [{ id: 1, url: images.keoDauPhong, alt: 'Kẹo đậu phộng' }],
        totalStars: 150,
        reviews: 33,
    },
    {
        id: 7,
        name: 'Me xí muội Huế',
        quantity: 60,
        price: 30000,
        description: 'Me chua ngọt xí muội, ăn vặt hấp dẫn của xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXiMuoi, alt: 'Me xí muội Huế' }],
        totalStars: 200,
        reviews: 45,
    },
    {
        id: 8,
        name: 'Mắm ruốc Huế',
        quantity: 35,
        price: 50000,
        description:
            'Mắm ruốc Huế lên men tự nhiên, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.mamRuot, alt: 'Mắm ruốc Huế' }],
        totalStars: 100,
        reviews: 22,
    },
    {
        id: 9,
        name: 'Hạt sen Huế sấy khô',
        quantity: 50,
        price: 75000,
        description:
            'Hạt sen khô thơm bùi, dùng nấu chè hoặc ăn vặt, đặc sản Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.hatSen, alt: 'Hạt sen' }],
        totalStars: 100,
        reviews: 25,
    },
    {
        id: 10,
        name: 'Bánh bột lọc Huế',
        quantity: 25,
        price: 45000,
        description: 'Bánh bột lọc nhân tôm thịt, dẻo thơm chuẩn vị Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [
            { id: 1, url: images.banhLoc.img1, alt: 'Bánh bột lọc Huế' },
            { id: 2, url: images.banhLoc.img2, alt: 'Bánh bột lọc Huế' },
        ],
        totalStars: 100,
        reviews: 35,
    },
    {
        id: 11,
        name: 'Nước mắm Nam Ô',
        quantity: 50,
        price: 80000,
        description:
            'Nước mắm Nam Ô Đà Nẵng làm từ cá cơm than, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'danang',
        idStore: '2',
        image: [{ id: 1, url: images.nuocMam, alt: 'Nước mắm Nam Ô' }],
        totalStars: 100,
        reviews: 20,
    },
    {
        id: 12,
        name: 'Mè xửng Huế',
        quantity: 40,
        price: 65000,
        description:
            'Mè xửng dẻo thơm, vị ngọt bùi của mạch nha, mè rang vàng óng, đặc sản truyền thống xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXungHue, alt: 'Mè xửng Huế' }],
        totalStars: 120,
        reviews: 25,
    },
    {
        id: 13,
        name: 'Kẹo cu đơ Hà Tĩnh',
        quantity: 30,
        price: 180000,
        description:
            'Kẹo cu đơ giòn rụm, nhân lạc và mạch nha ngọt bùi, đặc sản nổi tiếng của Hà Tĩnh.',
        category: 'snacks',
        area: 'hatinh',
        idStore: '4',
        image: [{ id: 1, url: images.keoCuDo, alt: 'Kẹo cu đơ Hà Tĩnh' }],
        totalStars: 80,
        reviews: 18,
    },
    {
        id: 14,
        name: 'Bánh tráng mè nướng Quảng Nam',
        quantity: 70,
        price: 25000,
        description: 'Bánh tráng giòn rụm, thơm mùi mè rang đặc sản Quảng Nam.',
        category: 'snacks',
        area: 'quangnam',
        idStore: '3',
        image: [{ id: 1, url: images.banhTrang, alt: 'Bánh tráng mè nướng' }],
        totalStars: 80,
        reviews: 19,
    },
    {
        id: 15,
        name: 'Trà cung đình Huế',
        quantity: 90,
        price: 90000,
        description:
            'Trà thảo mộc cung đình Huế kết hợp nhiều loại dược liệu quý.',
        category: 'drinks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.tra, alt: 'Trà cung đình Huế' }],
        totalStars: 100,
        reviews: 35,
    },
    {
        id: 16,
        name: 'Kẹo đậu phộng Quảng Ngãi',
        quantity: 100,
        price: 20000,
        description:
            'Kẹo truyền thống làm từ đậu phộng và đường mạch nha đặc sản Quảng Ngãi.',
        category: 'snacks',
        area: 'quangngai',
        idStore: '5',
        image: [{ id: 1, url: images.keoDauPhong, alt: 'Kẹo đậu phộng' }],
        totalStars: 150,
        reviews: 33,
    },
    {
        id: 17,
        name: 'Me xí muội Huế',
        quantity: 60,
        price: 30000,
        description: 'Me chua ngọt xí muội, ăn vặt hấp dẫn của xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXiMuoi, alt: 'Me xí muội Huế' }],
        totalStars: 200,
        reviews: 45,
    },
    {
        id: 18,
        name: 'Mắm ruốc Huế',
        quantity: 35,
        price: 50000,
        description:
            'Mắm ruốc Huế lên men tự nhiên, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.mamRuot, alt: 'Mắm ruốc Huế' }],
        totalStars: 100,
        reviews: 22,
    },
    {
        id: 19,
        name: 'Hạt sen Huế sấy khô',
        quantity: 50,
        price: 75000,
        description:
            'Hạt sen khô thơm bùi, dùng nấu chè hoặc ăn vặt, đặc sản Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.hatSen, alt: 'Hạt sen' }],
        totalStars: 100,
        reviews: 25,
    },
    {
        id: 20,
        name: 'Bánh bột lọc Huế',
        quantity: 25,
        price: 45000,
        description: 'Bánh bột lọc nhân tôm thịt, dẻo thơm chuẩn vị Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [
            { id: 1, url: images.banhLoc.img1, alt: 'Bánh bột lọc Huế' },
            { id: 2, url: images.banhLoc.img2, alt: 'Bánh bột lọc Huế' },
        ],
        totalStars: 100,
        reviews: 23,
    },
];

const listFavorites = [
    {
        userId: 1001,
        productIds: [2, 5, 7, 8, 9, 10, 12, 13, 14, 15, 16],
        storeIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    },
    {
        userId: 1002,
        productIds: [1, 3],
        storeIds: [1, 3, 5, 7],
    },
    {
        userId: 1003,
        productIds: [4, 6, 7, 10],
        storeIds: [2, 4, 6, 8],
    },
];

const listReviewProduct = [
    {
        id: 1,
        idProduct: 20,
        idUser: 1001,
        content: 'Sản phẩm rất tốt, đúng mô tả và giao hàng nhanh.',
        stars: 5,
        createdAt: '2025-08-10T14:30:00',
    },
    {
        id: 2,
        idProduct: 1,
        idUser: 1002,
        content: 'Chất lượng ổn trong tầm giá, sẽ ủng hộ lần sau.',
        stars: 4,
        createdAt: '2025-08-09T09:15:00',
    },
    {
        id: 3,
        idProduct: 1,
        idUser: 1003,
        content: 'Không giống như hình, chất liệu khá kém.',
        stars: 2,
        createdAt: '2025-08-08T19:45:00',
    },
    {
        id: 4,
        idProduct: 12,
        idUser: 1004,
        content: 'Sản phẩm ok, nhưng giao hàng hơi chậm.',
        stars: 3,
        createdAt: '2025-08-07T13:20:00',
    },
    {
        id: 5,
        idProduct: 1,
        idUser: 1005,
        content: 'Dịch vụ tốt, đóng gói kỹ, sản phẩm như quảng cáo.',
        stars: 5,
        createdAt: '2025-08-06T11:00:00',
    },
];

const reportForm = [
    {
        id: 'report',
        icon: faCircleExclamation,
        title: 'Báo cáo cửa hàng',
        description:
            'Khi bạn “Xác Nhận” thì nội dung báo cáo sẽ được gửi đến Quản Trị Viên. Quản Trị Viên sẽ xem xét và xử lý.',
    },
    {
        id: 'cancel',
        icon: faTriangleExclamation,
        title: 'Hủy đơn hàng',
        description:
            'Khi bạn “Xác Nhận” thì đơn hàng sẽ bị xóa. Thông báo gửi đến Chủ Cửa Hàng.',
    },
    {
        id: 'feedback',
        title: 'Đánh giá đơn hàng',
        star: true,
    },
    {
        id: 'Delete',
        icon: faTriangleExclamation,
        title: 'Xóa Sản Phẩm',
        description:
            'Khi bạn “Xác Nhận” thì Sản Phẩm này sẽ bị xóa khỏi hệ thống .',
        form: false,
    },
    {
        id: 'Delete',
        icon: faTriangleExclamation,
        title: 'Xóa Người Dùng',
        description:
            'Khi bạn “Xác Nhận” thì Người Dùng này sẽ bị xóa khỏi hệ thống .',
        form: true,
    },
    {
        id: 'block',
        icon: faTriangleExclamation,
        title: 'Khóa Tài Khoản Người Dùng',
        description:
            'Khi bạn “Xác Nhận” thì Người Dùng này sẽ bị khóa tài khoản .',
    },
    {
        id: 'Deletestore',
        icon: faTriangleExclamation,
        title: 'Xóa Cửa Hàng',
        description:
            'Khi bạn xác nhận thì cửa hàng sẽ bị xóa khỏi hệ thống. Lý do được gửi đến cho chủ cửa hàng.',
    },
    {
        id: 'blockstore',
        icon: faTriangleExclamation,
        title: 'Khóa Tài Khoản Cửa Hàng',
        description:
            'Khi bạn “Xác Nhận” thì Cửa Hàng này sẽ bị khóa tài khoản .',
    },
    {
        id: 'blockstore',
        icon: faTriangleExclamation,
        title: 'Mở Khóa Tài Khoản Cửa Hàng',
        description: 'Khi bạn “Xác Nhận” thì Cửa Hàng này sẽ Hoạt Động Lại .',
    },
    {
        id: 'blockuser',
        icon: faTriangleExclamation,
        title: 'Mở Khóa Tài Khoản ',
        description: 'Khi bạn “Xác Nhận” thì Tài Khoản này sẽ Hoạt Động Lại .',
    },
];

const slideImage = [
    images.thucPhamSach.img1,
    images.thucPhamSach.img2,
    images.thucPhamSach.img3,
];

const featuredCategories = [
    {
        id: 1,
        image: images.danhMucNoiBat.img1,
        title: 'Gia vị',
        categoryKey: 'dried',
    },
    {
        id: 2,
        image: images.danhMucNoiBat.img2,
        title: 'Trái cây - Rau củ',
        categoryKey: 'fruits',
    },
    {
        id: 3,
        image: images.danhMucNoiBat.img3,
        title: 'Bánh kẹo',
        categoryKey: 'snacks',
    },
    {
        id: 4,
        image: images.danhMucNoiBat.img4,
        title: 'Đồ khô - Chế biến sẵn',
        categoryKey: 'spices',
    },
];

const listAddress = [
    {
        id: 1,
        name: 'Nguyễn Văn A',
        phone: '03674373939',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1001,
    },
    {
        id: 2,
        name: 'Nguyễn Văn A',
        phone: '03674123939',
        address: 'thôn Phú Lương, xã Quảng Điền, Thành Phố Huế',
        userId: 1001,
    },
    {
        id: 3,
        name: 'Nguyễn Văn A',
        phone: '03672345675',
        address: 'thôn Đông Xuyên, xã Quảng Điền, Thành Phố Huế',
        userId: 1001,
    },
    {
        id: 4,
        name: 'Nguyễn Văn A',
        phone: '03601234939',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1001,
    },
    {
        id: 5,
        name: 'Nguyễn Văn A',
        phone: '03618237182',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1001,
    },
    {
        id: 6,
        name: 'Nguyễn Văn A',
        phone: '03888888888',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1001,
    },
    {
        id: 7,
        name: 'Nguyễn Văn A',
        phone: '02121212211',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1001,
    },
    {
        id: 8,
        name: 'Nguyễn Văn A',
        phone: '03674373939',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1002,
    },
    {
        id: 9,
        name: 'Nguyễn Văn A',
        phone: '03674373939',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1003,
    },
    {
        id: 10,
        name: 'Nguyễn Văn A',
        phone: '03674373939',
        address: 'thôn Phước Thanh, xã Quảng Điền, Thành Phố Huế',
        userId: 1004,
    },
];

const listinfoSell = [
    {
        idstore: 1,
        id: 1,
        Name: 'An',
        LastName: 'Nguyễn Phúc',
        Date: '26/04/20004',
        Gender: 'Nam',
        Email: 'npan2604@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '123',
    },
    {
        idstore: 2,
        id: 2,
        Name: 'Mạnh',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
    {
        idstore: 3,
        id: 3,
        Name: 'Mạnh',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
    {
        idstore: 4,
        id: 4,
        Name: 'Cường',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
    {
        idstore: 5,
        id: 5,
        Name: 'Tiến',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
    {
        idstore: 6,
        id: 6,
        Name: 'Dũng',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
    {
        idstore: 7,
        id: 7,
        Name: 'Nam',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
    {
        idstore: 8,
        id: 8,
        Name: 'Phước',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
    {
        idstore: 9,
        id: 9,
        Name: 'Tiến',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatarStore,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password: '1235',
    },
];
const listinforWalletSell = [
    {
        id: 1,
        idUser: 1,
        Name: 'Nguyễn Phúc An',
        Bank: 'Viettinbank',
        Banknumber: '01659835717',
        imgQR: images.avatar,
    },
];
const ListBank = [
    {
        label: 'viettinbank',
        value: 'viettinbank',
        img: images.imgBank.img2,
    },
    {
        label: 'MB',
        value: 'Mb',
        img: images.imgBank.img1,
    },
];
const listSelect = [
    {
        id: 1,
        name: 'Giá tiền',
        children: [
            { label: 'Dưới 100.000', value: [0, 100000], queryKey: 'price' },
            {
                label: '100.000 - 200.000',
                value: [100000, 200000],
                queryKey: 'price',
            },
            {
                label: '200.000 - 500.000',
                value: [200000, 500000],
                queryKey: 'price',
            },
            {
                label: 'Trên 500.000',
                value: [500000, Infinity],
                queryKey: 'price',
            },
        ],
    },
    {
        id: 2,
        name: 'Khu vực',
        children: [
            { label: 'Thanh Hóa', value: 'thanhhoa', queryKey: 'area' },
            { label: 'Nghệ An', value: 'nghean', queryKey: 'area' },
            { label: 'Hà Tĩnh', value: 'hatinh', queryKey: 'area' },
            { label: 'Quảng Bình', value: 'quangbinh', queryKey: 'area' },
            { label: 'Quảng Trị', value: 'quangtri', queryKey: 'area' },
            { label: 'Huế', value: 'hue', queryKey: 'area' },
            { label: 'Đà Nẵng', value: 'danang', queryKey: 'area' },
            { label: 'Quảng Nam', value: 'quangnam', queryKey: 'area' },
            { label: 'Quảng Ngãi', value: 'quangngai', queryKey: 'area' },
            { label: 'Bình Định', value: 'binhdinh', queryKey: 'area' },
            { label: 'Phú Yên', value: 'phuyen', queryKey: 'area' },
            { label: 'Khánh Hòa', value: 'khanhhoa', queryKey: 'area' },
            { label: 'Ninh Thuận', value: 'ninhthuan', queryKey: 'area' },
            { label: 'Bình Thuận', value: 'binhthuan', queryKey: 'area' },
        ],
    },
    {
        id: 3,
        name: 'Trạng thái',
        children: [
            { label: 'Đã hủy', value: 'cancelled', queryKey: 'status' },
            { label: 'Đã giao', value: 'approved', queryKey: 'status' },
            { label: 'Đang chờ duyệt', value: 'pending', queryKey: 'status' },
            { label: 'Đang giao hàng', value: 'shipping', queryKey: 'status' },
        ],
    },
    {
        id: 4,
        name: 'Năm',
        children: [
            { label: 'Năm', value: '0', queryKey: 'Year' },
            { label: 'Năm 2022', value: '2022', queryKey: 'Year' },
            { label: 'Năm 2023', value: '2023', queryKey: 'Year' },
            { label: 'Năm 2024', value: '2024', queryKey: 'Year' },
        ],
    },

    {
        id: 5,
        name: 'Tháng',
        children: [
            { label: 'Tháng ', value: '0', queryKey: 'Month' },
            { label: 'Tháng 1', value: '1', queryKey: 'Month' },
            { label: 'Tháng 2', value: '2', queryKey: 'Month' },
            { label: 'Tháng 3', value: '3', queryKey: 'Month' },
            { label: 'Tháng 4', value: '4', queryKey: 'Month' },
            { label: 'Tháng 5', value: '5', queryKey: 'Month' },
            { label: 'Tháng 6', value: '6', queryKey: 'Month' },
            { label: 'Tháng 7', value: '7', queryKey: 'Month' },
            { label: 'Tháng 8', value: '8', queryKey: 'Month' },
            { label: 'Tháng 9', value: '9', queryKey: 'Month' },
            { label: 'Tháng 10', value: '10', queryKey: 'Month' },
            { label: 'Tháng 11', value: '11', queryKey: 'Month' },
            { label: 'Tháng 12', value: '12', queryKey: 'Month' },
        ],
    },
    {
        id: 6,
        name: 'Tuần',
        children: [
            { label: 'Tuần ', value: '0', queryKey: 'Week' },
            { label: 'Tuần 1', value: '1', queryKey: 'Week' },
            { label: 'Tuần 2', value: '2', queryKey: 'Week' },
            { label: 'Tuần 3', value: '3', queryKey: 'Week' },
            { label: 'Tuần 4', value: '4', queryKey: 'Week' },
            { label: 'Tuần 5', value: '5', queryKey: 'Week' },
        ],
    },
    {
        id: 7,
        name: 'Trạng Thái',
        children: [
            { label: 'Tất Cả', value: '', queryKey: 'status' },
            { label: 'Hoạt Động', value: 'approved', queryKey: 'status' },
            { label: 'Khóa', value: 'block', queryKey: 'status' },
        ],
    },
    {
        id: 8,
        name: 'Trạng Thái',
        children: [
            { label: 'Tất Cả', value: '', queryKey: 'status' },
            { label: 'Chưa Duyệt', value: 'cancelled', queryKey: 'status' },
            { label: 'Hoạt Động', value: 'approved', queryKey: 'status' },
            { label: 'Khóa', value: 'block', queryKey: 'status' },
        ],
    },
    {
        id: 9,
        name: 'Hình thức giao hàng',
        children: [
            {
                label: 'Giao hàng tiêu chuẩn',
                value: 'STANDARD',
                description: 'Giao hàng trong vòng 5-7 ngày làm việc.',
                deliveryTime: '5-7 ngày',
                fee: 20000,
                queryKey: 'delivery',
            },
            {
                label: 'Giao hàng nhanh',
                value: 'EXPRESS',
                description: 'Giao hàng trong vòng 3-4 ngày làm việc.',
                deliveryTime: '3-4 ngày',
                fee: 35000,
                queryKey: 'delivery',
            },
            {
                label: 'Giao hàng hỏa tốc',
                value: 'SAME_DAY',
                description: 'Giao hàng trong vòng 1-2 ngày làm việc.',
                deliveryTime: '1-2 ngày',
                fee: 50000,
                queryKey: 'delivery',
            },
            {
                label: 'Giao hàng quốc tế',
                value: 'INTERNATIONAL',
                description: 'Giao hàng ra nước ngoài từ 7-14 ngày làm việc.',
                deliveryTime: '7-14 ngày',
                fee: 150000,
                queryKey: 'delivery',
            },
        ],
    },
    {
        id: 10,
        name: 'Phương thức thanh toán',
        children: [
            {
                label: 'Thanh toán khi nhận hàng',
                value: 'cod',
                queryKey: 'paymentMethod',
            },
            {
                label: 'Thanh toán QRCode',
                value: 'qrcode',
                queryKey: 'paymentMethod',
            },
        ],
    },
    {
        id: 11,
        name: 'Trạng Thái',
        children: [
            { label: 'Hoạt Động', value: 'active', queryKey: 'statusCoupon' },
            { label: 'Hết Hạn', value: 'expired', queryKey: 'statusCoupon' },
        ],
    },
    {
        id: 12,
        name: 'Loại Phiếu Giảm',
        children: [
            {
                label: 'Giảm phần trăm',
                value: 'percentage',
                queryKey: 'typeCoupon',
            },
            {
                label: 'Giảm số tiền',
                value: 'fixedAmount',
                queryKey: 'typeCoupon',
            },
            {
                label: 'Miễn phí vận chuyển',
                value: 'freeShipping',
                queryKey: 'typeCoupon',
            },
        ],
    },
];

const listOrders = [
    {
        id: 'DH00001',
        status: 'approved',
        userId: 1001,
        orderTime: '2025-08-06T11:00:00',
        discount: 20000,
        shippingFee: 20000,
        idAddress: 1,
        idProduct: 1,
        quantity: 2,
        reason: '',
    },
    {
        id: 'DH00002',
        status: 'cancelled',
        userId: 1001,
        orderTime: '2025-08-06T11:00:00',
        discount: 20000,
        shippingFee: 20000,
        idAddress: 1,
        idProduct: 3,
        quantity: 2,
        reason: 'Thông tin đơn hàng không hợp lệ!',
    },
    {
        id: 'DH00003',
        status: 'pending',
        userId: 1001,
        orderTime: '2025-08-06T11:00:00',
        discount: 20000,
        shippingFee: 20000,
        idAddress: 2,
        idProduct: 2,
        quantity: 1,
        reason: '',
    },
    {
        id: 'DH00004',
        status: 'shipping',
        userId: 1001,
        orderTime: '2025-08-06T11:00:00',
        discount: 20000,
        shippingFee: 20000,
        idAddress: 1,
        idProduct: 4,
        quantity: 3,
        reason: '',
    },
    {
        id: 'DH00005',
        status: 'shipping',
        userId: 1002,
        orderTime: '2025-08-06T11:00:00',
        discount: 20000,
        shippingFee: 20000,
        idAddress: 1,
        idProduct: 4,
        quantity: 3,
        reason: '',
    },
];

const listOrder = [
    {
        id: 1,
        idUser: 1,
        code: 'DH00123',
        status: 'approved',
        product: {
            name: 'Mè Xửng Huế',
            idOrder: 1001,
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
    {
        id: 2,
        idUser: 1,
        code: 'DH00124',
        status: 'shipping',
        product: {
            idOrder: 1002,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
    {
        id: 3,
        idUser: 1,
        code: 'DH00125',
        status: 'cancelled',
        product: {
            idOrder: 1003,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        reason: 'Thông tin đơn hàng không hợp lệ',
        img: images.keoCuDo,
    },
    {
        id: 4,
        idUser: 1,
        code: 'DH00126',
        status: 'pending',
        product: {
            idOrder: 1004,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
    {
        id: 5,
        idUser: 1,
        code: 'DH00123',
        status: 'approved',
        product: {
            name: 'Mè Xửng Huế',
            idOrder: 1001,
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
    {
        id: 6,
        idUser: 1,
        code: 'DH00124',
        status: 'shipping',
        product: {
            idOrder: 1002,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
    {
        id: 7,
        idUser: 1,
        code: 'DH00125',
        status: 'cancelled',
        product: {
            idOrder: 1003,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        reason: 'Thông tin đơn hàng không hợp lệ',
        img: images.keoCuDo,
    },
    {
        id: 8,
        idUser: 1,
        code: 'DH00126',
        status: 'pending',
        product: {
            idOrder: 1004,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
];

const listNotification = [
    {
        id: 1,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 2,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 3,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 4,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 5,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
    {
        id: 6,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 7,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 8,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 9,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 10,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
    {
        id: 11,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 12,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 13,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 14,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 15,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
    {
        id: 16,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 17,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 18,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 19,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 20,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
];
const listNotificationSell = [
    {
        id: 1,
        roll: 'user',
        senderId: 1001,
        receiverId: 1,
        content: `Đơn hàng mới từ Nguyễn Văn A (#DH00123) – 1.250.000₫.
Địa chỉ: 123 Đường ABC, Q.1, TP.HCM
SĐT: 0987 123 456`,
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 2,
        roll: 'user',
        senderId: 1002,
        receiverId: 1,
        content: `Đơn hàng mới từ Nguyễn Văn A (#DH00123) – 1.250.000₫.
Địa chỉ: 123 Đường ABC, Q.1, TP.HCM
SĐT: 0987 123 456`,
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 3,
        roll: 'user',
        senderId: 1001,
        receiverId: 1,
        content: `Đơn hàng mới từ Nguyễn Văn A (#DH00123) – 1.250.000₫. Đã Hủy`,
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 4,
        roll: 'user',
        senderId: 1001,
        receiverId: 1,
        content: `Đơn hàng mới từ Nguyễn Văn A (#DH00123) – 1.250.000₫.
Địa chỉ: 123 Đường ABC, Q.1, TP.HCM
SĐT: 0987 123 456`,
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 5,
        roll: 'user',
        senderId: 1002,
        receiverId: 1,
        content: `Đơn hàng mới từ Nguyễn Văn A (#DH00123) – 1.250.000₫.
Địa chỉ: 123 Đường ABC, Q.1, TP.HCM
SĐT: 0987 123 456`,
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 6,
        roll: 'user',
        senderId: 1001,
        receiverId: 1,
        content: `Đơn hàng mới từ Nguyễn Văn A (#DH00123) – 1.250.000₫. Đã Hủy`,
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
];
const listNotificationAdmin = [
    {
        id: 1,
        roll: 'store',
        senderId: 1,
        receiverId: 111,
        content: `Yêu Cầu Mở Cửa Hàng
Tên cửa hàng: Bếp Nhà
Giới thiệu cửa hàng: Bếp Nhà là nơi lưu giữ và lan tỏa những hương vị đặc sản đậm chất ...
SĐT: 0123 851 320`,
        timestamp: '2025-07-16T10:12:00',
        isRead: false,
    },
    {
        id: 2,
        roll: 'user',
        senderId: 1001,
        receiverId: 111,
        content: `Sản phẩm của cửa hàng HuyRon không đảm bảo an toàn vệ sinh thực phẩm yêu cầu
xóa bỏ sản phẩm mè xửng hoặc khóa cửa hàng`,
        timestamp: '2025-07-16T10:12:00',
        isRead: false,
    },
    {
        id: 3,
        roll: 'store',
        senderId: 1,
        receiverId: 111,
        content: `Yêu Cầu Mở Cửa Hàng
Tên cửa hàng: Bếp Nhà
Giới thiệu cửa hàng: Bếp Nhà là nơi lưu giữ và lan tỏa những hương vị đặc sản đậm chất ...
SĐT: 0123 851 320`,
        timestamp: '2025-07-16T10:12:00',
        isRead: false,
    },
    {
        id: 4,
        roll: 'user',
        senderId: 1001,
        receiverId: 111,
        content: `Sản phẩm của cửa hàng HuyRon không đảm bảo an toàn vệ sinh thực phẩm yêu cầu
xóa bỏ sản phẩm mè xửng hoặc khóa cửa hàng`,
        timestamp: '2025-07-16T10:12:00',
        isRead: false,
    },
];

const chatMessages = [
    {
        idChat: 'msg1',
        idSend: 1001,
        idReceive: 1,
        content: 'Chào shop, cho mình hỏi còn hàng không?',
        time: '2025-08-15T09:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg2',
        idSend: 1,
        idReceive: 1001,
        content: 'Dạ còn ạ, bạn cần hỗ trợ gì ạ?',
        time: '2025-08-15T09:01:00Z',
        type: 'text',
    },
    {
        idChat: 'msg3',
        idSend: 1001,
        idReceive: 1,
        content: 'Mình muốn mua 2 cái áo size M.',
        time: '2025-08-15T09:02:00Z',
        type: 'text',
    },
    {
        idChat: 'msg4',
        idSend: 1002,
        idReceive: 2,
        content: 'Shop có giao hàng nhanh không?',
        time: '2025-08-14T14:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg5',
        idSend: 2,
        idReceive: 1002,
        content: 'Dạ bên shop giao trong 2-3 ngày ạ.',
        time: '2025-08-14T14:05:00Z',
        type: 'text',
    },
    {
        idChat: 'msg6',
        idSend: 1002,
        idReceive: 2,
        content: 'Ok cảm ơn shop nhé!',
        time: '2025-08-14T14:06:00Z',
        type: 'text',
    },
    {
        idChat: 'msg7',
        idSend: 1003,
        idReceive: 3,
        content: 'Shop có size XXL không?',
        time: '2025-08-13T10:30:00Z',
        type: 'text',
    },
    {
        idChat: 'msg8',
        idSend: 3,
        idReceive: 1003,
        content: 'Dạ có bạn nhé, bạn muốn đặt bao nhiêu cái?',
        time: '2025-08-13T10:32:00Z',
        type: 'text',
    },
    {
        idChat: 'msg9',
        idSend: 1003,
        idReceive: 3,
        content: 'Mình đặt 3 cái, gửi về địa chỉ A nha shop.',
        time: '2025-08-13T10:35:00Z',
        type: 'text',
    },
    {
        idChat: 'msg10',
        idSend: 1004,
        idReceive: 1,
        content: 'Shop ơi, có giảm giá không?',
        time: '2025-08-12T15:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg11',
        idSend: 1,
        idReceive: 1004,
        content: 'Hiện tại shop đang có giảm 10% cho đơn hàng đầu tiên ạ.',
        time: '2025-08-12T15:01:00Z',
        type: 'text',
    },
    {
        idChat: 'msg12',
        idSend: 1004,
        idReceive: 1,
        content: 'Tuyệt quá, mình đặt luôn nhé.',
        time: '2025-08-12T15:02:00Z',
        type: 'text',
    },
    {
        idChat: 'msg13',
        idSend: 1005,
        idReceive: 2,
        content: 'Bạn có thể tư vấn giúp mình về sản phẩm X được không?',
        time: '2025-08-11T08:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg14',
        idSend: 2,
        idReceive: 1005,
        content: 'Dạ, bạn cần biết gì về sản phẩm X ạ?',
        time: '2025-08-11T08:05:00Z',
        type: 'text',
    },
    {
        idChat: 'msg15',
        idSend: 1005,
        idReceive: 2,
        content: 'Mình muốn biết kích thước và chất liệu.',
        time: '2025-08-11T08:10:00Z',
        type: 'text',
    },
    {
        idChat: 'msg16',
        idSend: 2,
        idReceive: 1001,
        content: 'Dạ còn ạ, bạn cần hỗ trợ gì ạ?',
        time: '2025-08-15T09:01:00Z',
        type: 'text',
    },
    {
        idChat: 'msg17',
        idSend: 1001,
        idReceive: 2,
        content: 'Mình muốn mua 2 cái áo size S.',
        time: '2025-08-15T09:02:00Z',
        type: 'text',
    },
];
const datachart = [
    {
        id: 1,
        name: 'Khách Hàng',
        value: 49,
    },
    {
        id: 2,
        name: 'Cửa Hàng',
        value: 30,
    },
    {
        id: 1,
        name: 'Cửa Hàng Chưa Duyệt',
        value: 21,
    },
];
const listCoupons = [
    {
        code: 'SALE10K',
        description: 'Giảm 10.000đ cho đơn từ 100.000đ',
        type: 'fixedAmount',
        value: 10000,
        startDate: '2025-08-01',
        endDate: '2025-08-31',
        quantity: 0,
        minOrderValue: 100000,
        status: 'active',
    },
    {
        code: 'FREESHIP',
        description: 'Miễn phí vận chuyển toàn quốc',
        type: 'freeShipping',
        value: 0,
        startDate: '2025-08-15',
        endDate: '2025-09-15',
        quantity: 1000,
        minOrderValue: 0,
        status: 'active',
    },
    {
        code: 'SUMMER25',
        description: 'Giảm 25% cho toàn bộ đơn hàng',
        type: 'percentage',
        value: 25,
        startDate: '2025-06-01',
        endDate: '2025-06-01',
        quantity: 200,
        minOrderValue: 0,
        status: 'expired',
    },
    {
        code: 'VIP50',
        description: 'Giảm 50% cho khách VIP',
        type: 'percentage',
        value: 50,
        startDate: '2025-08-01',
        endDate: '2025-12-31',
        quantity: 100,
        minOrderValue: 200000,
        status: 'active',
    },
    {
        code: 'FLASHSALE',
        description: 'Giảm 100.000đ trong 2 ngày Flash Sale',
        type: 'fixedAmount',
        value: 100000,
        startDate: '2025-08-25',
        endDate: '2025-08-27',
        quantity: 50,
        minOrderValue: 500000,
        status: 'active',
    },
    {
        code: 'BACK2SCHOOL',
        description: 'Giảm 15% mùa tựu trường',
        type: 'percentage',
        value: 15,
        startDate: '2025-08-20',
        endDate: '2025-09-10',
        quantity: 300,
        minOrderValue: 50000,
        status: 'active',
    },
];

export {
    listMenuUser,
    listMenuAdmin,
    listMenuSell,
    listProduct,
    reportForm,
    slideImage,
    featuredCategories,
    listSliderBarSell,
    listinfoSell,
    listinforWalletSell,
    listSelect,
    storeList,
    listUser,
    listReviewProduct,
    listOrder,
    ListBank,
    listNotification,
    chatMessages,
    listSidebarProfileUser,
    listSidebarProfileSell,
    listNotificationSell,
    listNotificationAdmin,
    datachart,
    listFavorites,
    listAddress,
    listOrders,
    listCoupons,
};
