import {
    faCircleExclamation,
    faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons';
import images from '~/assets/images/image';

const listUser = [
    {
        id: 1,
        roll:'Sell',
        name: 'Nguyễn Văn A',
        avatar: images.avatarStore,
        password: '123',
    },
    {
        id: 1001,
        name: 'Nguyễn Văn A',
        avatar: images.avatarStore,
        password: 'a123',
    },
    {
        id: 1002,
        name: 'Trần Thị B',
        avatar: images.avatarStore,
        password: 'b123',
    },
    {
        id: 1003,
        name: 'Lê Văn C',
        avatar: images.avatarStore,
        password: 'c123',
    },
    {
        id: 1004,
        name: 'Phạm Thị D',
        avatar: images.avatarStore,
        password: 'd123',
    },
    {
        id: 1005,
        name: 'Đặng Văn E',
        avatar: images.avatarStore,
        password: 'e123',
    },
];

const listMenuUser = [
    { name: 'Trang Chủ', path: '/UserHome' },
    {
        name: 'Sản Phẩm',
        path: '/UserProduct',
        children: [
            {
                name: 'Đồ khô - Chế biến sẵn',
                path: '/UserProduct?category=dried',
                categoryKey: 'dried',
            },
            {
                name: 'Bánh - Kẹo',
                path: '/UserProduct?category=snacks',
                categoryKey: 'snacks',
            },
            {
                name: 'Trái Cây - Rau Củ',
                path: '/UserProduct?category=fruits',
                categoryKey: 'fruits',
            },
            {
                name: 'Gia vị',
                path: '/UserProduct?category=spices',
                categoryKey: 'spices',
            },
            {
                name: 'Đồ uống',
                path: '/UserProduct?category=drinks',
                categoryKey: 'drinks',
            },
        ],
    },
    { name: 'Giới Thiệu', path: '/UserIntroduce' },
];

const listMenuAdmin = [
    { name: 'Thống Kế', path: '/StatisAdmin' },
    { name: 'Giới Thiệu', path: '/IntroduceAdmin' },
    { name: 'Quản Lý', path: '/ManagerUser' },
];

const listMenuSell = [
    { name: 'Sản Phẩm', path: '/ProductSell' },
    { name: 'Giới Thiệu', path: '/IntroduceSell' },
];
const listSliderBarSell = [
    { name: 'Hồ sơ của tôi', path: '/ProfileSell' },
    { name: 'Cửa hàng của tôi', path: '/StoreSell' },
    { name: 'Đổi mật khẩu', path: '/PasswordSell' },
    { name: 'Thống kê', path: '/StatisticSell' },
    { name: 'Duyệt đơn hàng', path: '/OrderSell' },
    { name: 'Ví', path: '/WalletSell' },
    { name: 'Đăng xuất', path: '/' },
];

const storeList = [
    {
        idUser: 1,
        idBank:1,
        name: 'Bếp Nhà',
        description:
            'Bếp Nhà là nơi lưu giữ và lan tỏa những hương vị đặc sản đậm chất miền Trung Việt Nam. Từ những món quà quê dân dã đến các sản phẩm truyền thống được chế biến tinh tế, chúng tôi mong muốn mang đến cho bạn không chỉ là món ăn, mà còn là một phần ký ức, một chút ấm áp của quê hương.',
        address: '125 Trường Chinh, TP. Huế',
        phone: '0935 123 456',
        email: 'contact@bepnha.vn',
        website: 'https://www.bepnha.vn',
        fanpage: 'https://www.fb.com/bepnhadacsan',
        rating: 4.8,
        totalReviews: 898,
        joinedAt: '2018-08-01',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: ['Mè xửng Huế', 'Me xí muội Huế', 'Trà Huế'],
        guarantee: {
            ingredients: 'Nguyên liệu sạch, chuẩn vị quê nhà',
            quality: 'Đóng gói kỹ lưỡng, giao hàng toàn quốc',
            refund: 'Tư vấn tận tình, đổi trả dễ dàng nếu sản phẩm không như cam kết',
        },
        area: 'hue',
    },
    {
        id: 2,
        name: 'Đặc Sản Đà Nẵng',
        description:
            'Mang hương vị của thành phố biển đến từng bữa ăn, Đặc Sản Đà Nẵng chuyên cung cấp các sản phẩm như nước mắm Nam Ô, tré Bà Đệ, bánh khô mè truyền thống.',
        address: '78 Nguyễn Văn Linh, TP. Đà Nẵng',
        phone: '0905 234 567',
        email: 'contact@dacsandanang.vn',
        website: 'https://www.dacsandanang.vn',
        fanpage: 'https://www.fb.com/dacsandanang',
        rating: 4.5,
        totalReviews: 500,
        joinedAt: '2019-05-15',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Nước mắm Nam Ô',
            'Tré Bà Đệ',
            'Bánh khô mè',
            'Chả bò Đà Nẵng',
        ],
        guarantee: {
            ingredients: 'Chọn lọc từ vùng biển Đà Nẵng',
            quality: 'Chế biến an toàn, đóng gói kỹ',
            refund: 'Hoàn tiền nếu sản phẩm không đúng mô tả',
        },
        area: 'danang',
    },
    {
        id: 3,
        name: 'Quảng Nam Quê Tôi',
        description:
            'Gìn giữ hương vị dân dã của vùng đất Quảng Nam qua từng món đặc sản như bánh tráng mè, mỳ Quảng, bánh tổ, bánh in truyền thống.',
        address: '45 Trần Cao Vân, Tam Kỳ, Quảng Nam',
        phone: '0911 111 222',
        email: 'info@quangnamquetoi.vn',
        website: 'https://www.quangnamquetoi.vn',
        fanpage: 'https://www.fb.com/quangnamquetoi',
        rating: 4.2,
        totalReviews: 310,
        joinedAt: '2020-02-10',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Bánh tráng mè nướng Quảng Nam',
            'Bánh tổ',
            'Mỳ Quảng',
        ],
        guarantee: {
            ingredients: 'Chế biến theo công thức gia truyền',
            quality: 'Sạch, ngon, đúng vị quê hương',
            refund: 'Hỗ trợ đổi trả trong 7 ngày',
        },
        area: 'quangnam',
    },
    {
        id: 4,
        name: 'Hà Tĩnh Đặc Sản',
        description:
            'Hà Tĩnh Đặc Sản là nơi hội tụ những món ngon nổi tiếng như kẹo cu đơ, cam Khe Mây, bánh đa, tương Nam Đàn, gói ghém hương vị miền Trung xa xứ.',
        address: '10 Lê Duẩn, TP. Hà Tĩnh',
        phone: '0922 333 444',
        email: 'support@hattinhdacsan.vn',
        website: 'https://www.hattinhdacsan.vn',
        fanpage: 'https://www.fb.com/hattinhdacsan',
        rating: 4.1,
        totalReviews: 180,
        joinedAt: '2021-04-05',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: ['Kẹo cu đơ Hà Tĩnh', 'Cam Khe Mây', 'Tương Nam Đàn'],
        guarantee: {
            ingredients: 'Nguyên liệu bản địa, quy trình thủ công',
            quality: 'Hương vị truyền thống, đóng gói chuẩn',
            refund: 'Hoàn tiền nếu sản phẩm không đạt yêu cầu',
        },
        area: 'hatinh',
    },
    {
        id: 5,
        name: 'Quảng Ngãi Quê Hương',
        description:
            'Đưa đặc sản Quảng Ngãi đến gần hơn với mọi miền, chúng tôi cung cấp các sản phẩm như kẹo gương, kẹo đậu phộng, cá bống sông Trà, mạch nha,...',
        address: '66 Hùng Vương, TP. Quảng Ngãi',
        phone: '0988 555 666',
        email: 'hello@quangngai.vn',
        website: 'https://www.quangngai.vn',
        fanpage: 'https://www.fb.com/quangngaiquehuong',
        rating: 4.3,
        totalReviews: 250,
        joinedAt: '2019-11-20',
        avatar: images.avatarStore,
        certifications: [
            { id: 1, url: images.giayChungNhan.img1, alt: 'Giấy chứng nhận' },
            { id: 2, url: images.giayChungNhan.img2, alt: 'Giấy hoạt động' },
        ],
        featuredProducts: [
            'Kẹo đậu phộng Quảng Ngãi',
            'Cá bống sông Trà',
            'Mạch nha Quảng Ngãi',
        ],
        guarantee: {
            ingredients: 'Chọn lọc kỹ lưỡng từ địa phương',
            quality: 'Đóng gói an toàn, giữ trọn hương vị',
            refund: 'Đổi trả nếu không hài lòng',
        },
        area: 'quangngai',
    },
];

const listProduct = [
    {
        id: 1,
        name: 'Nước mắm Nam Ô',
        quantity: 50,
        price: 80000,
        description:
            'Nước mắm Nam Ô Đà Nẵng làm từ cá cơm than, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'danang',
        idStore: '2',
        image: [{ id: 1, url: images.nuocMam, alt: 'Nước mắm Nam Ô' }],
        totalStars: 100,
        reviews: 20,
    },
    {
        id: 2,
        name: 'Mè xửng Huế',
        quantity: 40,
        price: 65000,
        description:
            'Mè xửng dẻo thơm, vị ngọt bùi của mạch nha, mè rang vàng óng, đặc sản truyền thống xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXungHue, alt: 'Mè xửng Huế' }],
        totalStars: 120,
        reviews: 25,
    },
    {
        id: 3,
        name: 'Kẹo cu đơ Hà Tĩnh',
        quantity: 30,
        price: 180000,
        description:
            'Kẹo cu đơ giòn rụm, nhân lạc và mạch nha ngọt bùi, đặc sản nổi tiếng của Hà Tĩnh.',
        category: 'snacks',
        area: 'hatinh',
        idStore: '4',
        image: [{ id: 1, url: images.keoCuDo, alt: 'Kẹo cu đơ Hà Tĩnh' }],
        totalStars: 80,
        reviews: 18,
    },
    {
        id: 4,
        name: 'Bánh tráng mè nướng Quảng Nam',
        quantity: 70,
        price: 25000,
        description: 'Bánh tráng giòn rụm, thơm mùi mè rang đặc sản Quảng Nam.',
        category: 'snacks',
        area: 'quangnam',
        idStore: '3',
        image: [{ id: 1, url: images.banhTrang, alt: 'Bánh tráng mè nướng' }],
        totalStars: 80,
        reviews: 19,
    },
    {
        id: 5,
        name: 'Trà cung đình Huế',
        quantity: 90,
        price: 90000,
        description:
            'Trà thảo mộc cung đình Huế kết hợp nhiều loại dược liệu quý.',
        category: 'drinks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.tra, alt: 'Trà cung đình Huế' }],
        totalStars: 100,
        reviews: 21,
    },
    {
        id: 6,
        name: 'Kẹo đậu phộng Quảng Ngãi',
        quantity: 100,
        price: 20000,
        description:
            'Kẹo truyền thống làm từ đậu phộng và đường mạch nha đặc sản Quảng Ngãi.',
        category: 'snacks',
        area: 'quangngai',
        idStore: '5',
        image: [{ id: 1, url: images.keoDauPhong, alt: 'Kẹo đậu phộng' }],
        totalStars: 150,
        reviews: 33,
    },
    {
        id: 7,
        name: 'Me xí muội Huế',
        quantity: 60,
        price: 30000,
        description: 'Me chua ngọt xí muội, ăn vặt hấp dẫn của xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXiMuoi, alt: 'Me xí muội Huế' }],
        totalStars: 200,
        reviews: 45,
    },
    {
        id: 8,
        name: 'Mắm ruốc Huế',
        quantity: 35,
        price: 50000,
        description:
            'Mắm ruốc Huế lên men tự nhiên, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.mamRuot, alt: 'Mắm ruốc Huế' }],
        totalStars: 100,
        reviews: 22,
    },
    {
        id: 9,
        name: 'Hạt sen Huế sấy khô',
        quantity: 50,
        price: 75000,
        description:
            'Hạt sen khô thơm bùi, dùng nấu chè hoặc ăn vặt, đặc sản Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.hatSen, alt: 'Hạt sen' }],
        totalStars: 100,
        reviews: 25,
    },
    {
        id: 10,
        name: 'Bánh bột lọc Huế',
        quantity: 25,
        price: 45000,
        description: 'Bánh bột lọc nhân tôm thịt, dẻo thơm chuẩn vị Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [
            { id: 1, url: images.banhLoc.img1, alt: 'Bánh bột lọc Huế' },
            { id: 2, url: images.banhLoc.img2, alt: 'Bánh bột lọc Huế' },
        ],
        totalStars: 100,
        reviews: 23,
    },
    {
        id: 11,
        name: 'Nước mắm Nam Ô',
        quantity: 50,
        price: 80000,
        description:
            'Nước mắm Nam Ô Đà Nẵng làm từ cá cơm than, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'danang',
        idStore: '2',
        image: [{ id: 1, url: images.nuocMam, alt: 'Nước mắm Nam Ô' }],
        totalStars: 100,
        reviews: 20,
    },
    {
        id: 12,
        name: 'Mè xửng Huế',
        quantity: 40,
        price: 65000,
        description:
            'Mè xửng dẻo thơm, vị ngọt bùi của mạch nha, mè rang vàng óng, đặc sản truyền thống xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXungHue, alt: 'Mè xửng Huế' }],
        totalStars: 120,
        reviews: 25,
    },
    {
        id: 13,
        name: 'Kẹo cu đơ Hà Tĩnh',
        quantity: 30,
        price: 180000,
        description:
            'Kẹo cu đơ giòn rụm, nhân lạc và mạch nha ngọt bùi, đặc sản nổi tiếng của Hà Tĩnh.',
        category: 'snacks',
        area: 'hatinh',
        idStore: '4',
        image: [{ id: 1, url: images.keoCuDo, alt: 'Kẹo cu đơ Hà Tĩnh' }],
        totalStars: 80,
        reviews: 18,
    },
    {
        id: 14,
        name: 'Bánh tráng mè nướng Quảng Nam',
        quantity: 70,
        price: 25000,
        description: 'Bánh tráng giòn rụm, thơm mùi mè rang đặc sản Quảng Nam.',
        category: 'snacks',
        area: 'quangnam',
        idStore: '3',
        image: [{ id: 1, url: images.banhTrang, alt: 'Bánh tráng mè nướng' }],
        totalStars: 80,
        reviews: 19,
    },
    {
        id: 15,
        name: 'Trà cung đình Huế',
        quantity: 90,
        price: 90000,
        description:
            'Trà thảo mộc cung đình Huế kết hợp nhiều loại dược liệu quý.',
        category: 'drinks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.tra, alt: 'Trà cung đình Huế' }],
        totalStars: 100,
        reviews: 21,
    },
    {
        id: 16,
        name: 'Kẹo đậu phộng Quảng Ngãi',
        quantity: 100,
        price: 20000,
        description:
            'Kẹo truyền thống làm từ đậu phộng và đường mạch nha đặc sản Quảng Ngãi.',
        category: 'snacks',
        area: 'quangngai',
        idStore: '5',
        image: [{ id: 1, url: images.keoDauPhong, alt: 'Kẹo đậu phộng' }],
        totalStars: 150,
        reviews: 33,
    },
    {
        id: 17,
        name: 'Me xí muội Huế',
        quantity: 60,
        price: 30000,
        description: 'Me chua ngọt xí muội, ăn vặt hấp dẫn của xứ Huế.',
        category: 'snacks',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.meXiMuoi, alt: 'Me xí muội Huế' }],
        totalStars: 200,
        reviews: 45,
    },
    {
        id: 18,
        name: 'Mắm ruốc Huế',
        quantity: 35,
        price: 50000,
        description:
            'Mắm ruốc Huế lên men tự nhiên, hương vị đậm đà đặc trưng.',
        category: 'spices',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.mamRuot, alt: 'Mắm ruốc Huế' }],
        totalStars: 100,
        reviews: 22,
    },
    {
        id: 19,
        name: 'Hạt sen Huế sấy khô',
        quantity: 50,
        price: 75000,
        description:
            'Hạt sen khô thơm bùi, dùng nấu chè hoặc ăn vặt, đặc sản Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [{ id: 1, url: images.hatSen, alt: 'Hạt sen' }],
        totalStars: 100,
        reviews: 25,
    },
    {
        id: 20,
        name: 'Bánh bột lọc Huế',
        quantity: 25,
        price: 45000,
        description: 'Bánh bột lọc nhân tôm thịt, dẻo thơm chuẩn vị Huế.',
        category: 'dried',
        area: 'hue',
        idStore: '1',
        image: [
            { id: 1, url: images.banhLoc.img1, alt: 'Bánh bột lọc Huế' },
            { id: 2, url: images.banhLoc.img2, alt: 'Bánh bột lọc Huế' },
        ],
        totalStars: 100,
        reviews: 23,
    },
];

const listReviewProduct = [
    {
        id: 1,
        idProduct: 20,
        idUser: 1001,
        content: 'Sản phẩm rất tốt, đúng mô tả và giao hàng nhanh.',
        stars: 5,
        createdAt: '2025-08-10T14:30:00',
    },
    {
        id: 2,
        idProduct: 1,
        idUser: 1002,
        content: 'Chất lượng ổn trong tầm giá, sẽ ủng hộ lần sau.',
        stars: 4,
        createdAt: '2025-08-09T09:15:00',
    },
    {
        id: 3,
        idProduct: 1,
        idUser: 1003,
        content: 'Không giống như hình, chất liệu khá kém.',
        stars: 2,
        createdAt: '2025-08-08T19:45:00',
    },
    {
        id: 4,
        idProduct: 12,
        idUser: 1004,
        content: 'Sản phẩm ok, nhưng giao hàng hơi chậm.',
        stars: 3,
        createdAt: '2025-08-07T13:20:00',
    },
    {
        id: 5,
        idProduct: 1,
        idUser: 1005,
        content: 'Dịch vụ tốt, đóng gói kỹ, sản phẩm như quảng cáo.',
        stars: 5,
        createdAt: '2025-08-06T11:00:00',
    },
];

const reportForm = [
    {
        id: 'report',
        icon: faCircleExclamation,
        title: 'Báo cáo cửa hàng',
        description:
            'Khi bạn “Xác Nhận” thì nội dung báo cáo sẽ được gửi đến Quản Trị Viên. Quản Trị Viên sẽ xem xét và xử lý.',
    },
    {
        id: 'cancel',
        icon: faTriangleExclamation,
        title: 'Hủy đơn hàng',
        description:
            'Khi bạn “Xác Nhận” thì đơn hàng sẽ bị xóa. Thông báo gửi đến Chủ Cửa Hàng.',
    },
    {
        id: 'feedback',
        title: 'Đánh giá đơn hàng',
        star: true,
    },
];

const slideImage = [
    images.thucPhamSach.img1,
    images.thucPhamSach.img2,
    images.thucPhamSach.img3,
];

const featuredCategories = [
    {
        id: 1,
        image: images.danhMucNoiBat.img1,
        title: 'Gia vị',
    },
    {
        id: 2,
        image: images.danhMucNoiBat.img2,
        title: 'Trái cây - Rau củ',
    },
    {
        id: 3,
        image: images.danhMucNoiBat.img3,
        title: 'Bánh kẹo',
    },
    {
        id: 4,
        image: images.danhMucNoiBat.img4,
        title: 'Đồ khô - Chế biến sẵn',
    },
];
const listinfoSell = [
    {
        idUser:1,
        id: 1,
        Name: 'An',
        LastName: 'Nguyễn Phúc',
        Date: '26/04/20004',
        Gender: 'Nam',
        Email: 'npan2604@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatar,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password:'123'
    },
        {
        id: 2,
        Name: 'Mạnh',
        LastName: 'Nguyễn Hoàng',
        Date: '28/05/20005',
        Gender: 'Nam',
        Email: 'n24@gmail.com',
        Phone: '01659835717',
        Facebook: 'trungmart',
        Tiktok: 'trungmart@168',
        Avatar: images.avatar,
        Address: 'thôn, Phước Thanh, xã Quảng Điền, TP. Huế',
        password:'1235'
    },
];
const listinforWalletSell = [
    {
        id: 1,
        idUser:1,
        Name: 'Nguyễn Phúc An',
        Bank: 'Viettinbank',
        Banknumber: '01659835717',
        imgQR: images.avatar,
    },
];
const ListBank = [
    {
        label: 'viettinbank',
        value: 'viettinbank',
        img: images.imgBank.img2,
    },
    {
        label: 'MB',
        value: 'Mb',
        img: images.imgBank.img1,
    },
];
const listSelect = [
    {
        id: 1,
        name: 'Giá tiền',
        children: [
            { label: 'Dưới 100.000', value: [0, 100000], queryKey: 'price' },
            {
                label: '100.000 - 200.000',
                value: [100000, 200000],
                queryKey: 'price',
            },
            {
                label: '200.000 - 500.000',
                value: [200000, 500000],
                queryKey: 'price',
            },
            {
                label: 'Trên 500.000',
                value: [500000, Infinity],
                queryKey: 'price',
            },
        ],
    },
    {
        id: 2,
        name: 'Khu vực',
        children: [
            { label: 'Thanh Hóa', value: 'thanhhoa', queryKey: 'area' },
            { label: 'Nghệ An', value: 'nghean', queryKey: 'area' },
            { label: 'Hà Tĩnh', value: 'hatinh', queryKey: 'area' },
            { label: 'Quảng Bình', value: 'quangbinh', queryKey: 'area' },
            { label: 'Quảng Trị', value: 'quangtri', queryKey: 'area' },
            { label: 'Huế', value: 'hue', queryKey: 'area' },
            { label: 'Đà Nẵng', value: 'danang', queryKey: 'area' },
            { label: 'Quảng Nam', value: 'quangnam', queryKey: 'area' },
            { label: 'Quảng Ngãi', value: 'quangngai', queryKey: 'area' },
            { label: 'Bình Định', value: 'binhdinh', queryKey: 'area' },
            { label: 'Phú Yên', value: 'phuyen', queryKey: 'area' },
            { label: 'Khánh Hòa', value: 'khanhhoa', queryKey: 'area' },
            { label: 'Ninh Thuận', value: 'ninhthuan', queryKey: 'area' },
            { label: 'Bình Thuận', value: 'binhthuan', queryKey: 'area' },
        ],
    },
    {
        id: 3,
        name: 'Trạng thái',
        children: [
            { label: 'Đã hủy', value: 'cancelled', queryKey: 'status' },
            { label: 'Đã duyệt', value: 'approved', queryKey: 'status' },
            { label: 'Đang chờ duyệt', value: 'pending', queryKey: 'status' },
            { label: 'Đang giao hàng', value: 'shipping', queryKey: 'status' },
        ],
    },
    {
    id: 4,
    name: "Năm",
    children: [
        {label: "Năm",value:"0",queryKey: 'Year'},
        {label: "Năm 2022",value: "2022",queryKey: 'Year'},
        {label: "Năm 2023",value: "2023",queryKey: 'Year'},
        {label: "Năm 2024",value: "2024",queryKey: 'Year'},  
        ]
    },

    {
    id: 5,
    name: "Tháng",
    children: [
    {label: "Tháng ",value:"0",queryKey: 'Month'},
    {label: "Tháng 1",value:"1",queryKey: 'Month'},
    {label: "Tháng 2",value:"2",queryKey: 'Month'},
    {label: "Tháng 3",value:"3",queryKey: 'Month'},
    {label: "Tháng 4",value:"4",queryKey: 'Month'},
    {label: "Tháng 5",value:"5",queryKey: 'Month'},
    {label: "Tháng 6",value:"6",queryKey: 'Month'},
    {label: "Tháng 7",value:"7",queryKey: 'Month'},
    {label: "Tháng 8",value:"8",queryKey: 'Month'},
    {label: "Tháng 9",value:"9",queryKey: 'Month'},
    {label: "Tháng 10",value: "10",queryKey: 'Month'},
    {label: "Tháng 11",value: "11",queryKey: 'Month'},
    {label: "Tháng 12",value: "12",queryKey: 'Month'},
    ]
    },
    {
    id: 6,
    name: "Tuần",
    children: [
    {label: "Tuần ",value:"0",queryKey: 'Week'},
    {label: "Tuần 1",value:"1",queryKey: 'Week'},
    {label: "Tuần 2",value:"2",queryKey: 'Week'},
    {label: "Tuần 3",value:"3",queryKey: 'Week'},
    {label: "Tuần 4",value:"4",queryKey: 'Week'},
    {label: "Tuần 5",value:"5",queryKey: 'Week'},
    ]
    },



];
const listOrder = [
    {
        id: 1,
        idUser:1,
        code: 'DH00123',
        status: 'approved',
        product: {
            name: 'Mè Xửng Huế',
            idOrder:1001,
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
    {
        id: 2,
        idUser:1,
        code: 'DH00124',
        status: 'shipping',
        product: {
            idOrder:1002,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
    {
        id: 3,
        idUser:1,

        code: 'DH00125',
        status: 'cancelled',
        product: {
            idOrder:1003,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        reason: 'Thông tin đơn hàng không hợp lệ',
        img: images.keoCuDo,
    },
    {
        id: 4,
        idUser:1,
        code: 'DH00126',
        status: 'pending',
        product: {
            idOrder:1004,
            name: 'Mè Xửng Huế',
            price: 281000,
            quantity: 1,
            description: 'Địa Chỉ Giao : 126 Nguyễn Kim Thành, ...',
            receiverName: 'Nguyễn Phúc An',
            phone: '0357284698',
        },
        discount: 50000,
        shippingFee: 20000,
        orderTime: '19/07/2025 - 10:15 AM',
        img: images.keoCuDo,
    },
];

const listNotification = [
    {
        id: 1,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 2,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 3,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 4,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 5,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
    {
        id: 6,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 7,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 8,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 9,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 10,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
    {
        id: 11,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 12,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 13,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 14,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 15,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
    {
        id: 16,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T09:30:00',
        isRead: false,
    },
    {
        id: 17,
        senderId: 1,
        receiverId: 1002,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T08:45:00',
        isRead: true,
    },
    {
        id: 18,
        senderId: 1,
        receiverId: 1001,
        content:
            'Đơn hàng của bạn đã giao thành công, shop mong chờ những đóng góp của bạn để shop ngày càng phát triển.',
        timestamp: '2025-08-13T17:20:00',
        isRead: true,
    },
    {
        id: 19,
        senderId: 2,
        receiverId: 1003,
        content:
            'Đơn hàng của bạn đã được xác nhận, shop đang đóng gói và giao đơn hàng đến với bạn trong thời gian sớm nhất.',
        timestamp: '2025-08-14T07:10:00',
        isRead: false,
    },
    {
        id: 20,
        senderId: 1,
        receiverId: 1001,
        content: 'Đơn hàng của bạn đã bị hủy vì không hợp lệ.',
        timestamp: '2025-08-13T15:00:00',
        isRead: true,
    },
];

const chatMessages = [
    {
        idChat: 'msg1',
        idSend: 1001,
        idReceive: 1,
        content: 'Chào shop, cho mình hỏi còn hàng không?',
        time: '2025-08-15T09:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg2',
        idSend: 1,
        idReceive: 1001,
        content: 'Dạ còn ạ, bạn cần hỗ trợ gì ạ?',
        time: '2025-08-15T09:01:00Z',
        type: 'text',
    },
    {
        idChat: 'msg3',
        idSend: 1001,
        idReceive: 1,
        content: 'Mình muốn mua 2 cái áo size M.',
        time: '2025-08-15T09:02:00Z',
        type: 'text',
    },
    {
        idChat: 'msg4',
        idSend: 1002,
        idReceive: 2,
        content: 'Shop có giao hàng nhanh không?',
        time: '2025-08-14T14:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg5',
        idSend: 2,
        idReceive: 1002,
        content: 'Dạ bên shop giao trong 2-3 ngày ạ.',
        time: '2025-08-14T14:05:00Z',
        type: 'text',
    },
    {
        idChat: 'msg6',
        idSend: 1002,
        idReceive: 2,
        content: 'Ok cảm ơn shop nhé!',
        time: '2025-08-14T14:06:00Z',
        type: 'text',
    },
    {
        idChat: 'msg7',
        idSend: 1003,
        idReceive: 3,
        content: 'Shop có size XXL không?',
        time: '2025-08-13T10:30:00Z',
        type: 'text',
    },
    {
        idChat: 'msg8',
        idSend: 3,
        idReceive: 1003,
        content: 'Dạ có bạn nhé, bạn muốn đặt bao nhiêu cái?',
        time: '2025-08-13T10:32:00Z',
        type: 'text',
    },
    {
        idChat: 'msg9',
        idSend: 1003,
        idReceive: 3,
        content: 'Mình đặt 3 cái, gửi về địa chỉ A nha shop.',
        time: '2025-08-13T10:35:00Z',
        type: 'text',
    },
    {
        idChat: 'msg10',
        idSend: 1004,
        idReceive: 1,
        content: 'Shop ơi, có giảm giá không?',
        time: '2025-08-12T15:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg11',
        idSend: 1,
        idReceive: 1004,
        content: 'Hiện tại shop đang có giảm 10% cho đơn hàng đầu tiên ạ.',
        time: '2025-08-12T15:01:00Z',
        type: 'text',
    },
    {
        idChat: 'msg12',
        idSend: 1004,
        idReceive: 1,
        content: 'Tuyệt quá, mình đặt luôn nhé.',
        time: '2025-08-12T15:02:00Z',
        type: 'text',
    },
    {
        idChat: 'msg13',
        idSend: 1005,
        idReceive: 2,
        content: 'Bạn có thể tư vấn giúp mình về sản phẩm X được không?',
        time: '2025-08-11T08:00:00Z',
        type: 'text',
    },
    {
        idChat: 'msg14',
        idSend: 2,
        idReceive: 1005,
        content: 'Dạ, bạn cần biết gì về sản phẩm X ạ?',
        time: '2025-08-11T08:05:00Z',
        type: 'text',
    },
    {
        idChat: 'msg15',
        idSend: 1005,
        idReceive: 2,
        content: 'Mình muốn biết kích thước và chất liệu.',
        time: '2025-08-11T08:10:00Z',
        type: 'text',
    },
    {
        idChat: 'msg16',
        idSend: 2,
        idReceive: 1001,
        content: 'Dạ còn ạ, bạn cần hỗ trợ gì ạ?',
        time: '2025-08-15T09:01:00Z',
        type: 'text',
    },
    {
        idChat: 'msg17',
        idSend: 1001,
        idReceive: 2,
        content: 'Mình muốn mua 2 cái áo size S.',
        time: '2025-08-15T09:02:00Z',
        type: 'text',
    },
];

export {
    listMenuUser,
    listMenuAdmin,
    listMenuSell,
    listProduct,
    reportForm,
    slideImage,
    featuredCategories,
    listSliderBarSell,
    listinfoSell,
    listinforWalletSell,
    listSelect,
    storeList,
    listUser,
    listReviewProduct,
    listOrder,
    ListBank,
    listNotification,
    chatMessages,
};
